### PR TITLE
Use C++20.

### PR DESCRIPTION
**Pull request by tez011**
## Description

#2149 was reverted in #2320 and needs to be split into three changes:

- C++20 (this one!)
- UCRT64
- WGC

## Type of Change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Dependency update (updates to dependencies)
- [ ] Documentation update (changes to documentation)
- [ ] Repository update (changes to repository files, e.g. `.github/...`)

## Checklist
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added or updated the in code docstring/documentation-blocks for new or existing methods/components

## Branch Updates
LizardByte requires that branches be up-to-date before merging. This means that after any PR is merged, this branch
must be updated before it can be merged. You must also
[Allow edits from maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- [x] I want maintainers to keep my branch updated

### CODE REVIEW

**Comment by tez011** [comment]
https://stackoverflow.com/questions/62723053/boost-log-expressions-v1-71-will-not-compile-under-c20

**Comment by tez011** [comment]
I guess the linux builds are failing because boost 1.74 and c++20 don't play super well together. (1.74 *is* from 2020).

A glance at package versioning shows that our boost is pretty inconsistent between platforms and linux distributions. Windows uses 1.83 at the time of writing, Mac uses 1.81, Linux uses something between 1.74 and 1.81.

Where boost is versioned, could we bump it to 1.81?

**Comment by tez011** [comment]
AppImage build fails because Ubuntu 20.04 provides only Boost 1.71, which is incompatible with C++20. https://stackoverflow.com/questions/62723053/boost-log-expressions-v1-71-will-not-compile-under-c20

There is a more recent LTS version. Could we drop 20.04? Even Debian 11 provides 1.74.

**Comment by tez011** [comment]
What wonderful timing!
CI passes on my fork.

**Comment by tez011** [comment]
depends on #2327

**Comment by ReenigneArcher** [comment]
> depends on #2327

Merged.

File: src/platform/linux/input.cpp [hunk 1]
```diff
@@ -1510,7 +1510,7 @@ namespace platf {
     std::stringstream ss;
     ss << std::hex << std::setfill('0');
     for (const auto &ch : str) {
-      ss << ch;
+      ss << static_cast<uint_least32_t>(ch);
```
Comment (tez011) [inline src/platform/linux/input.cpp:1513]: >char32_t — type for UTF-32 character representation, required to be large enough to represent any UTF-32 code unit (32 bits). It has the same size, signedness, and alignment as [std::uint_least32_t](https://en.cppreference.com/w/cpp/types/integer), but is a distinct type.
https://en.cppreference.com/w/cpp/language/types#char32_t

Therefore we should expect no data loss with a static_cast to uint_least32_t

File: src/platform/linux/kmsgrab.cpp [hunk 2]
```diff
@@ -614,7 +614,7 @@ namespace platf {
         for (auto &entry : fs::directory_iterator { card_dir }) {
           auto file = entry.path().filename();
 
-          auto filestring = file.generic_u8string();
+          auto filestring = file.generic_string();
```
Comment (tez011) [inline src/platform/linux/kmsgrab.cpp:617]: generic_u8string now returns `basic_string<char8_t>`. since char8_t is unsigned, this is now incompatible with `std::string_view = std::basic_string_view<char>`. Assuming this goes in with the UCRT64 change our locale is not exactly guaranteed to be utf-8 either, and the comparison we're immediately making is to an ANSI string so the u8-ness seems mostly irrelevant here. Therefore, making this change so compilation succeeds.

**Comment by tez011** [comment]
Is there anything else in this pull request I should handle before it's able to be merged?

**Comment by tez011** [comment]
Hi! Just waiting for testing/approval results for this pull request. This first change is fairly small so I'm hoping there aren't too many obstacles!

**Comment by ReenigneArcher** [comment]
@tez011 sorry for the delays. We have a lot of open PRs. It might take a little bit before the other approvals come in. I think we are going to try to put out another patch to get a few things fixed before merging these bigger ones.

Can you rebase your branch on top of the latest nightly?

File: cmake/targets/common.cmake [hunk 3]
```diff
@@ -36,7 +36,7 @@ endif()
 
 target_link_libraries(sunshine ${SUNSHINE_EXTERNAL_LIBRARIES} ${EXTRA_LIBS})
 target_compile_definitions(sunshine PUBLIC ${SUNSHINE_DEFINITIONS})
-set_target_properties(sunshine PROPERTIES CXX_STANDARD 17
+set_target_properties(sunshine PROPERTIES CXX_STANDARD 20
         VERSION ${PROJECT_VERSION}
         SOVERSION ${PROJECT_VERSION_MAJOR})
```
Comment (FrogTheFrog) [inline cmake/targets/common.cmake:42]: Just below we have:
```
target_compile_options(sunshine PRIVATE $<$<COMPILE_LANGUAGE:CXX>:${SUNSHINE_COMPILE_OPTIONS}>;$<$<COMPILE_LANGUAGE:CUDA>:${SUNSHINE_COMPILE_OPTIONS_CUDA};-std=c++17>)
```
This either need to be changed to c++20 or removed? @ReenigneArcher do you know why we need to specify the standard explicitly again?

^ This includes here and in other files.

File: src/network.cpp [hunk 4]
```diff
@@ -169,7 +170,9 @@ namespace net {
   addr_to_url_escaped_string(boost::asio::ip::address address) {
     address = normalize_address(address);
     if (address.is_v6()) {
-      return "["s + address.to_string() + ']';
+      std::stringstream ss;
```
Comment (FrogTheFrog) [inline src/network.cpp:173]: This change to me seems unnecessary? Why was this needed? Some reallocations might be avoided, but is it worth it?

File: src/platform/linux/input.cpp (hunk 1 above)
Comment (FrogTheFrog) [inline src/platform/linux/input.cpp:1513]: Why are we casting? The `char32_t` is already unsigned.

File: src/platform/linux/kmsgrab.cpp (hunk 2 above)
Comment (FrogTheFrog) [reply src/platform/linux/kmsgrab.cpp:617]: Good thing is that we don't use `file.generic_string();` on Windows. Yet...

File: src/stream.h [hunk 5]
```diff
@@ -3,6 +3,7 @@
  * @brief todo
  */
 #pragma once
+#include <utility>
```
Comment (FrogTheFrog) [inline src/stream.h:6]: There are a lot of includes for this. Are they really needed? Especially here, in the header.

File: cmake/targets/common.cmake (hunk 3 above)
Comment (tez011) [reply cmake/targets/common.cmake:42]: I settled on this change after trying both options you describe. The cuda compiler doesn't support c++20.

File: src/stream.h (hunk 5 above)
Comment (tez011) [reply src/stream.h:6]: Yes. Compilation fails otherwise.

File: src/platform/linux/input.cpp (hunk 1 above)
Comment (tez011) [reply src/platform/linux/input.cpp:1513]: stringstreams don't approve of mixing type `char` and type `char32_t`. (You can try this.) This cast is done to force the stringstream to recognize that this value is a 32-bit integer and to hex it accordingly.

Comment (tez011) [reply src/platform/linux/input.cpp:1513]:
```
/home/runner/work/Sunshine/Sunshine/src/platform/linux/input.cpp: In function ‘std::string platf::to_hex(const std::__cxx11::basic_string<char32_t>&)’:
/home/runner/work/Sunshine/Sunshine/src/platform/linux/input.cpp:1513:13: error: use of deleted function ‘std::basic_ostream<char, _Traits>& std::operator<<(std::basic_ostream<char, _Traits>&, char32_t) [with _Traits = std::char_traits<char>]’
 1513 |       ss << ch;
      |             ^~
In file included from /usr/include/c++/10/bits/unique_ptr.h:42,
                 from /usr/include/c++/10/bits/locale_conv.h:41,
                 from /usr/include/c++/10/locale:43,
                 from /usr/include/boost/locale/boundary/facets.hpp:17,
                 from /usr/include/boost/locale/boundary.hpp:12,
                 from /usr/include/boost/locale.hpp:11,
                 from /home/runner/work/Sunshine/Sunshine/src/platform/linux/input.cpp:21:
/usr/include/c++/10/ostream:553:5: note: declared here
  553 |     operator<<(basic_ostream<char, _Traits>&, char32_t) = delete;
      |     ^~~~~~~~
make[2]: *** [tests/CMakeFiles/test_sunshine.dir/build.make:665: tests/CMakeFiles/test_sunshine.dir/__/src/platform/linux/input.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:271: tests/CMakeFiles/test_sunshine.dir/all] Error 2
```

File: src/network.cpp (hunk 4 above)
Comment (tez011) [reply src/network.cpp:173]: I seem to recall that under C++20, the return type of `boost::asio::ip::address::to_string()` changes which makes "summing" these illegal using the current syntax. I can't find the compilation error in my CI history though.

I might have been able to fix it by adding parentheses, but we use stringstreams elsewhere in sunshine (see another patch in this change), so I figured this would be fine.

File: src/stream.h (hunk 5 above)
Comment (tez011) [reply src/stream.h:6]: It seems they are needed before any boost includes, otherwise a lot of errors like this are observed:
https://github.com/tez011/Sunshine/actions/runs/8484576885/job/23247793427

If we can include a boost header in here, we can certainly include a system header above it, no?

Comment (FrogTheFrog) [reply src/stream.h:6]: No problems with that, it's just that currently include state in Sunshine is a mess. For example, in this file even include `asio`, but it not used anywhere...

But that's out of scope for this PR.

**Comment by FrogTheFrog** [comment]
@ReenigneArcher LGTM

File: cmake/targets/common.cmake (hunk 3 above)
Comment (ReenigneArcher) [reply cmake/targets/common.cmake:42]: I'm looking to bump to c++23 in https://github.com/LizardByte/Sunshine/pull/4096 and came here just to see what all was changed when bumping to 20. It looks like the bump to 23 will be quite a bit easier than the one to 20, as everything is just building right away.

It seems that with cuda we can specify the standard directly in the file name, though I'm not sure that's a good idea? https://docs.nvidia.com/cuda/cuda-compiler-driver-nvcc/index.html#std-c-03-c-11-c-14-c-17-c-20-std

It also seems that at least recent versions of cuda now support c++20. Perhaps this can be set dynamically.
