### ISSUE TITLE
MacOS homebrew install fails on make

### ISSUE THREAD

**Issue by nekitk** [LizardByte/Sunshine#3683]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Is your issue described in the documentation?

- [x] I have read the documentation

### Is your issue present in the latest beta/pre-release?

This issue is present in the latest pre-release

### Describe the Bug

Running `brew install sunshine` or `sunshine-beta` fails on `make` step.

### Expected Behavior

Should install without errors

### Additional Context

Homebrew 4.4.21

### Host Operating System

macOS

### Operating System Version

15.3

### Architecture

arm64/aarch64

### Sunshine commit or version

-

### Package

macOS - Homebrew

### GPU Type

AMD

### GPU Model

Apple M1 Pro

### GPU Driver/Mesa Version

-

### Capture Method

None

### Config

```Shell

```

### Apps

```json

```

### Relevant log output

```shell
==> cmake -S . -B build -DBUILD_WERROR=ON -DHOMEBREW_ALLOW_FETCHCONTENT=ON -DOPENSSL_ROOT_DIR=/opt/homebrew/opt/openssl@3 -
==> make
Last 15 lines from /Users/chill/Library/Logs/Homebrew/sunshine-beta/02.make:
../../../../build/assets/web/assets/_plugin-vue_export-helper-e3be04f7.css  320.97 kB │ gzip:  53.82 kB
../../../../build/assets/web/assets/password-e7073e71.js                      0.59 kB │ gzip:   0.38 kB
../../../../build/assets/web/assets/welcome-c7ccff22.js                       0.62 kB │ gzip:   0.40 kB
../../../../build/assets/web/assets/pin-daae1379.js                           0.82 kB │ gzip:   0.41 kB
../../../../build/assets/web/assets/ResourceCard-27b0a959.js                  1.72 kB │ gzip:   0.66 kB
../../../../build/assets/web/assets/Checkbox-32ab7a74.js                      2.11 kB │ gzip:   1.04 kB
../../../../build/assets/web/assets/troubleshooting-2b5c95ad.js               2.20 kB │ gzip:   0.86 kB
../../../../build/assets/web/assets/index-f2823a0e.js                         2.91 kB │ gzip:   1.14 kB
../../../../build/assets/web/assets/apps-9628d30a.js                          3.89 kB │ gzip:   1.56 kB
../../../../build/assets/web/assets/Navbar-819f254a.js                        6.16 kB │ gzip:   2.32 kB
../../../../build/assets/web/assets/config-57459fc8.js                       57.33 kB │ gzip:  12.24 kB
../../../../build/assets/web/assets/_plugin-vue_export-helper-917c8565.js   339.54 kB │ gzip: 116.90 kB
✓ built in 1.10s
[ 14%] Built target web-ui
make: *** [all] Error 2
```

**Comment by ReenigneArcher** [comment]
If you provide only the last 15 lines of the logs, that's not enough to figure anything out.

**Comment by nekitk** [comment]
Here's the full output:
```bash
brew install sunshine-beta
==> Fetching lizardbyte/homebrew/sunshine-beta
==> Cloning https://github.com/LizardByte/Sunshine.git
Cloning into '/Users/chill/Library/Caches/Homebrew/sunshine-beta--git'...
==> Checking out tag v2025.221.143652
HEAD is now at e3079da1 ci(flatpak): build aarch64 on arm architecture (#3680)
Submodule 'packaging/linux/flatpak/deps/flatpak-builder-tools' (https://github.com/flatpak/flatpak-builder-tools.git) registered for path 'packaging/linux/flatpak/deps/flatpak-builder-tools'
Submodule 'packaging/linux/flatpak/deps/shared-modules' (https://github.com/flathub/shared-modules.git) registered for path 'packaging/linux/flatpak/deps/shared-modules'
Submodule 'third-party/Simple-Web-Server' (https://gitlab.com/eidheim/Simple-Web-Server.git) registered for path 'third-party/Simple-Web-Server'
Submodule 'third-party/TPCircularBuffer' (https://github.com/michaeltyson/TPCircularBuffer.git) registered for path 'third-party/TPCircularBuffer'
Submodule 'third-party/ViGEmClient' (https://github.com/LizardByte/Virtual-Gamepad-Emulation-Client.git) registered for path 'third-party/ViGEmClient'
Submodule 'third-party/build-deps' (https://github.com/LizardByte/build-deps.git) registered for path 'third-party/build-deps'
Submodule 'third-party/doxyconfig' (https://github.com/LizardByte/doxyconfig.git) registered for path 'third-party/doxyconfig'
Submodule 'third-party/googletest' (https://github.com/google/googletest.git) registered for path 'third-party/googletest'
Submodule 'third-party/inputtino' (https://github.com/games-on-whales/inputtino.git) registered for path 'third-party/inputtino'
Submodule 'third-party/libdisplaydevice' (https://github.com/LizardByte/libdisplaydevice.git) registered for path 'third-party/libdisplaydevice'
Submodule 'third-party/moonlight-common-c' (https://github.com/moonlight-stream/moonlight-common-c.git) registered for path 'third-party/moonlight-common-c'
Submodule 'third-party/nanors' (https://github.com/sleepybishop/nanors.git) registered for path 'third-party/nanors'
Submodule 'third-party/nv-codec-headers' (https://github.com/FFmpeg/nv-codec-headers.git) registered for path 'third-party/nv-codec-headers'
Submodule 'third-party/nvapi-open-source-sdk' (https://github.com/LizardByte/nvapi-open-source-sdk.git) registered for path 'third-party/nvapi-open-source-sdk'
Submodule 'third-party/tray' (https://github.com/LizardByte/tray.git) registered for path 'third-party/tray'
Submodule 'third-party/wayland-protocols' (https://gitlab.freedesktop.org/wayland/wayland-protocols.git) registered for path 'third-party/wayland-protocols'
Submodule 'third-party/wlr-protocols' (https://gitlab.freedesktop.org/wlroots/wlr-protocols.git) registered for path 'third-party/wlr-protocols'
Cloning into '/Users/chill/Library/Caches/Homebrew/sunshine-beta--git/packaging/linux/flatpak/deps/flatpak-builder-tools'...
Cloning into '/Users/chill/Library/Caches/Homebrew/sunshine-beta--git/packaging/linux/flatpak/deps/shared-modules'...
Cloning into '/Users/chill/Library/Caches/Homebrew/sunshine-beta--git/third-party/Simple-Web-Server'...
Cloning into '/Users/chill/Library/Caches/Homebrew/sunshine-beta--git/third-party/TPCircularBuffer'...
Cloning into '/Users/chill/Library/Caches/Homebrew/sunshine-beta--git/third-party/ViGEmClient'...
Cloning into '/Users/chill/Library/Caches/Homebrew/sunshine-beta--git/third-party/build-deps'...
Cloning into '/Users/chill/Library/Caches/Homebrew/sunshine-beta--git/third-party/doxyconfig'...
Cloning into '/Users/chill/Library/Caches/Homebrew/sunshine-beta--git/third-party/googletest'...
Cloning into '/Users/chill/Library/Caches/Homebrew/sunshine-beta--git/third-party/inputtino'...
Cloning into '/Users/chill/Library/Caches/Homebrew/sunshine-beta--git/third-party/libdisplaydevice'...
Cloning into '/Users/chill/Library/Caches/Homebrew/sunshine-beta--git/third-party/moonlight-common-c'...
Cloning into '/Users/chill/Library/Caches/Homebrew/sunshine-beta--git/third-party/nanors'...
Cloning into '/Users/chill/Library/Caches/Homebrew/sunshine-beta--git/third-party/nv-codec-headers'...
Cloning into '/Users/chill/Library/Caches/Homebrew/sunshine-beta--git/third-party/nvapi-open-source-sdk'...
Cloning into '/Users/chill/Library/Caches/Homebrew/sunshine-beta--git/third-party/tray'...
Cloning into '/Users/chill/Library/Caches/Homebrew/sunshine-beta--git/third-party/wayland-protocols'...
Cloning into '/Users/chill/Library/Caches/Homebrew/sunshine-beta--git/third-party/wlr-protocols'...
Submodule path 'packaging/linux/flatpak/deps/flatpak-builder-tools': checked out 'aac65cf44cd4e008594a9d9ac1db08e2025067a6'
Submodule path 'packaging/linux/flatpak/deps/shared-modules': checked out '85cf3273f89eeede7dcb301f77a7ced32fecaa3a'
Submodule path 'third-party/Simple-Web-Server': checked out '4abe3491582b56c0b18fc35278aad33b2db29cdc'
Submodule path 'third-party/TPCircularBuffer': checked out '8833b3a73fab6530cc51e2063a85cced01714cfb'
Submodule path 'third-party/ViGEmClient': checked out '8d71f6740ffff4671cdadbca255ce528e3cd3fef'
Submodule path 'third-party/build-deps': checked out '249a31384468c3b01e06a58a1a39b12a292f2f86'
Submodule path 'third-party/doxyconfig': checked out '4501c7b191170cd2adcc12336821b65449186d85'
Submodule 'doxygen-awesome-css' (https://github.com/jothepro/doxygen-awesome-css.git) registered for path 'third-party/doxyconfig/doxygen-awesome-css'
Cloning into '/Users/chill/Library/Caches/Homebrew/sunshine-beta--git/third-party/doxyconfig/doxygen-awesome-css'...
Submodule path 'third-party/doxyconfig/doxygen-awesome-css': checked out '98dd024a650e71d8afd1215c27134aa779bdbbd7'
Submodule path 'third-party/googletest': checked out '6910c9d9165801d8827d628cb72eb7ea9dd538c5'
Submodule path 'third-party/inputtino': checked out '00ea0c28e87298b983831262896ee780a426a29c'
Submodule path 'third-party/libdisplaydevice': checked out '591387c58465376540fc9f505e938860e08fd47e'
Submodule 'third-party/doxyconfig' (https://github.com/LizardByte/doxyconfig.git) registered for path 'third-party/libdisplaydevice/third-party/doxyconfig'
Submodule 'third-party/googletest' (https://github.com/google/googletest.git) registered for path 'third-party/libdisplaydevice/third-party/googletest'
Cloning into '/Users/chill/Library/Caches/Homebrew/sunshine-beta--git/third-party/libdisplaydevice/third-party/doxyconfig'...
Cloning into '/Users/chill/Library/Caches/Homebrew/sunshine-beta--git/third-party/libdisplaydevice/third-party/googletest'...
Submodule path 'third-party/libdisplaydevice/third-party/doxyconfig': checked out '4501c7b191170cd2adcc12336821b65449186d85'
Submodule 'doxygen-awesome-css' (https://github.com/jothepro/doxygen-awesome-css.git) registered for path 'third-party/libdisplaydevice/third-party/doxyconfig/doxygen-awesome-css'
Cloning into '/Users/chill/Library/Caches/Homebrew/sunshine-beta--git/third-party/libdisplaydevice/third-party/doxyconfig/doxygen-awesome-css'...
Submodule path 'third-party/libdisplaydevice/third-party/doxyconfig/doxygen-awesome-css': checked out '98dd024a650e71d8afd1215c27134aa779bdbbd7'
Submodule path 'third-party/libdisplaydevice/third-party/googletest': checked out 'f8d7d77c06936315286eb55f8de22cd23c188571'
Submodule path 'third-party/moonlight-common-c': checked out 'd3d3e6cf015cd032ce02718246b52aabd1e12294'
Submodule 'enet' (https://github.com/cgutman/enet.git) registered for path 'third-party/moonlight-common-c/enet'
Cloning into '/Users/chill/Library/Caches/Homebrew/sunshine-beta--git/third-party/moonlight-common-c/enet'...
Submodule path 'third-party/moonlight-common-c/enet': checked out '44c85e16279553d9c052e572bcbfcd745fb74abf'
Submodule path 'third-party/nanors': checked out '19f07b513e924e471cadd141943c1ec4adc8d0e0'
Submodule path 'third-party/nv-codec-headers': checked out '22441b505d9d9afc1e3002290820909846c24bdc'
Submodule path 'third-party/nvapi-open-source-sdk': checked out 'cce4e90b629f712ae6eebafac97739bd1196cdef'
Submodule path 'third-party/tray': checked out 'd45306e686c90a18f5792a1541783d7bc8555bc6'
Submodule 'third-party/doxyconfig' (https://github.com/LizardByte/doxyconfig.git) registered for path 'third-party/tray/third-party/doxyconfig'
Submodule 'third-party/googletest' (https://github.com/google/googletest.git) registered for path 'third-party/tray/third-party/googletest'
Cloning into '/Users/chill/Library/Caches/Homebrew/sunshine-beta--git/third-party/tray/third-party/doxyconfig'...
Cloning into '/Users/chill/Library/Caches/Homebrew/sunshine-beta--git/third-party/tray/third-party/googletest'...
Submodule path 'third-party/tray/third-party/doxyconfig': checked out '4501c7b191170cd2adcc12336821b65449186d85'
Submodule 'doxygen-awesome-css' (https://github.com/jothepro/doxygen-awesome-css.git) registered for path 'third-party/tray/third-party/doxyconfig/doxygen-awesome-css'
Cloning into '/Users/chill/Library/Caches/Homebrew/sunshine-beta--git/third-party/tray/third-party/doxyconfig/doxygen-awesome-css'...
Submodule path 'third-party/tray/third-party/doxyconfig/doxygen-awesome-css': checked out '98dd024a650e71d8afd1215c27134aa779bdbbd7'
Submodule path 'third-party/tray/third-party/googletest': checked out 'f8d7d77c06936315286eb55f8de22cd23c188571'
Submodule path 'third-party/wayland-protocols': checked out 'c7b582cb71ec145026a547dcd8abb9dfeba40541'
Submodule path 'third-party/wlr-protocols': checked out 'ffb89ac790096f6e6272822c8d5df7d0cc6fcdfa'
/Users/chill/Library/Caches/Homebrew/sunshine-beta--git/packaging/linux/flatpak/deps/flatpak-builder-tools
/Users/chill/Library/Caches/Homebrew/sunshine-beta--git/packaging/linux/flatpak/deps/shared-modules
/Users/chill/Library/Caches/Homebrew/sunshine-beta--git/third-party/Simple-Web-Server
/Users/chill/Library/Caches/Homebrew/sunshine-beta--git/third-party/TPCircularBuffer
/Users/chill/Library/Caches/Homebrew/sunshine-beta--git/third-party/ViGEmClient
/Users/chill/Library/Caches/Homebrew/sunshine-beta--git/third-party/build-deps
/Users/chill/Library/Caches/Homebrew/sunshine-beta--git/third-party/doxyconfig
/Users/chill/Library/Caches/Homebrew/sunshine-beta--git/third-party/doxyconfig/doxygen-awesome-css
/Users/chill/Library/Caches/Homebrew/sunshine-beta--git/third-party/googletest
/Users/chill/Library/Caches/Homebrew/sunshine-beta--git/third-party/inputtino
/Users/chill/Library/Caches/Homebrew/sunshine-beta--git/third-party/libdisplaydevice
/Users/chill/Library/Caches/Homebrew/sunshine-beta--git/third-party/libdisplaydevice/third-party/doxyconfig
/Users/chill/Library/Caches/Homebrew/sunshine-beta--git/third-party/libdisplaydevice/third-party/doxyconfig/doxygen-awesome-css
/Users/chill/Library/Caches/Homebrew/sunshine-beta--git/third-party/libdisplaydevice/third-party/googletest
/Users/chill/Library/Caches/Homebrew/sunshine-beta--git/third-party/moonlight-common-c
/Users/chill/Library/Caches/Homebrew/sunshine-beta--git/third-party/moonlight-common-c/enet
/Users/chill/Library/Caches/Homebrew/sunshine-beta--git/third-party/nanors
/Users/chill/Library/Caches/Homebrew/sunshine-beta--git/third-party/nv-codec-headers
/Users/chill/Library/Caches/Homebrew/sunshine-beta--git/third-party/nvapi-open-source-sdk
/Users/chill/Library/Caches/Homebrew/sunshine-beta--git/third-party/tray
/Users/chill/Library/Caches/Homebrew/sunshine-beta--git/third-party/tray/third-party/doxyconfig
/Users/chill/Library/Caches/Homebrew/sunshine-beta--git/third-party/tray/third-party/doxyconfig/doxygen-awesome-css
/Users/chill/Library/Caches/Homebrew/sunshine-beta--git/third-party/tray/third-party/googletest
/Users/chill/Library/Caches/Homebrew/sunshine-beta--git/third-party/wayland-protocols
/Users/chill/Library/Caches/Homebrew/sunshine-beta--git/third-party/wlr-protocols
==> Installing sunshine-beta from lizardbyte/homebrew
==> Building docs: disabled
==> Disabled statically linking Boost libraries
==> cmake -S . -B build -DBUILD_WERROR=ON -DHOMEBREW_ALLOW_FETCHCONTENT=ON -DOPENSSL_ROOT_DIR=/opt/homebrew/opt/openssl@3 -
==> make
Last 15 lines from /Users/chill/Library/Logs/Homebrew/sunshine-beta/02.make:
../../../../build/assets/web/assets/_plugin-vue_export-helper-e3be04f7.css  320.97 kB │ gzip:  53.82 kB
../../../../build/assets/web/assets/password-e7073e71.js                      0.59 kB │ gzip:   0.38 kB
../../../../build/assets/web/assets/welcome-c7ccff22.js                       0.62 kB │ gzip:   0.40 kB
../../../../build/assets/web/assets/pin-daae1379.js                           0.82 kB │ gzip:   0.41 kB
../../../../build/assets/web/assets/ResourceCard-27b0a959.js                  1.72 kB │ gzip:   0.66 kB
../../../../build/assets/web/assets/Checkbox-32ab7a74.js                      2.11 kB │ gzip:   1.04 kB
../../../../build/assets/web/assets/troubleshooting-2b5c95ad.js               2.20 kB │ gzip:   0.86 kB
../../../../build/assets/web/assets/index-f2823a0e.js                         2.91 kB │ gzip:   1.14 kB
../../../../build/assets/web/assets/apps-9628d30a.js                          3.89 kB │ gzip:   1.56 kB
../../../../build/assets/web/assets/Navbar-819f254a.js                        6.16 kB │ gzip:   2.32 kB
../../../../build/assets/web/assets/config-57459fc8.js                       57.33 kB │ gzip:  12.24 kB
../../../../build/assets/web/assets/_plugin-vue_export-helper-917c8565.js   339.54 kB │ gzip: 116.90 kB
✓ built in 1.10s
[ 14%] Built target web-ui
make: *** [all] Error 2

If reporting this issue please do so at (not Homebrew/brew or Homebrew/homebrew-core):
  https://github.com/lizardbyte/homebrew-homebrew/issues
```

**Comment by Jumerry** [comment]
==> Installing lizardbyte/homebrew/sunshine
==> Building docs: disabled
==> Disabled statically linking Boost libraries
==> cmake -S . -B build -DBUILD_WERROR=ON -DHOMEBREW_ALLOW_FETCHCONTENT=ON -DOPE
Last 15 lines from /Users/zyc/Library/Logs/Homebrew/sunshine/01.cmake:


-- nlohmann_json v3.11.x package not found in the system. Falling back to FetchContent.
-- Using the multi-header code from /tmp/sunshine-20250225-57047-qul1y0/build/_deps/json-src/include/
CMake Warning at third-party/libdisplaydevice/src/CMakeLists.txt:10 (message):
  MacOS is not supported yet.


-- Found OpenSSL: /opt/homebrew/opt/openssl@3/lib/libcrypto.dylib (found version "3.4.1")
-- Found PkgConfig: /opt/homebrew/bin/pkg-config (found version "2.3.0")
-- Checking for module 'libcurl'
--   Found libcurl, version 8.12.1
-- Checking for module 'miniupnpc'
--   Found miniupnpc, version 2.3.1
-- Configuring incomplete, errors occurred!

If reporting this issue please do so at (not Homebrew/brew or Homebrew/homebrew-core):
  https://github.com/lizardbyte/homebrew-homebrew/issues

**Comment by ReenigneArcher** [comment]
@nekitk your error is here:

```
In file included from /tmp/sunshine-beta-20250222-42064-c160mz/third-party/libdisplaydevice/src/common/json_serializer.cpp:8:
/tmp/sunshine-beta-20250222-42064-c160mz/third-party/libdisplaydevice/src/common/include/display_device/types.h:8:10: fatal error: 'cstdint' file not found
    8 | #include <cstdint>
      |          ^~~~~~~~~
In file included from /tmp/sunshine-beta-20250222-42064-c160mz/third-party/libdisplaydevice/src/common/file_settings_persistence.cpp:6:
/tmp/sunshine-beta-20250222-42064-c160mz/third-party/libdisplaydevice/src/common/include/display_device/file_settings_persistence.h:8:10: fatal error: 'filesystem' file not found
    8 | #include <filesystem>
      |          ^~~~~~~~~~~~
1 error generated.
In file included from /tmp/sunshine-beta-20250222-42064-c160mz/third-party/libdisplaydevice/src/common/logging.cpp:10:
/tmp/sunshine-beta-20250222-42064-c160mz/third-party/libdisplaydevice/src/common/include/display_device/logging.h:8:10: fatal error: 'functional' file not found
    8 | #include <functional>
      |          ^~~~~~~~~~~~
In file included from /tmp/sunshine-beta-20250222-42064-c160mz/third-party/libdisplaydevice/src/common/json.cpp:6:
/tmp/sunshine-beta-20250222-42064-c160mz/third-party/libdisplaydevice/src/common/include/display_device/json.h:8:10: fatal error: 'set' file not found
    8 | #include <set>
      |          ^~~~~
In file included from /tmp/sunshine-beta-20250222-42064-c160mz/third-party/googletest/googletest/src/gtest-all.cc:38:
/tmp/sunshine-beta-20250222-42064-c160mz/third-party/googletest/googletest/include/gtest/gtest.h:52:10: fatal error: 'cstddef' file not found
   52 | #include <cstddef>
      |          ^~~~~~~~~
1 error generated.
```

What's the fix though? I don't know at this point. As far as I know these are part of the standard library.

**Comment by benjaminwootton** [comment]
Instaling the latest xcode fixed this for me.   I don't really understand gcc setup on OSX, but both the default and the brew version threw up this error.  After installing xcode from the app store it built succesfully.

**Comment by dkpoulsen** [comment]
I somehow managed to fix it by using Claude 
here are the instructions I followed, I wont recommend it cause I'm slight tipsy.
https://claude.ai/share/1831c295-f19b-466f-9724-af74fec78239

**Comment by XiongjieDai** [comment]
After tried thoudans of method with chatgpt and deepseek, and checked with 

> I somehow managed to fix it by using Claude here are the instructions I followed, I wont recommend it cause I'm slight tipsy. https://claude.ai/share/1831c295-f19b-466f-9724-af74fec78239


Any kind of Force Sunshine’s Build to Use the Correct Libraries like

```
cmake -S . -B build \
  -DOPENSSL_ROOT_DIR=/opt/homebrew/opt/openssl@3 \
  -DOPENSSL_SSL_LIBRARY=/opt/homebrew/opt/openssl@3/lib/libssl.dylib \
  -DOPENSSL_CRYPTO_LIBRARY=/opt/homebrew/opt/openssl@3/lib/libcrypto.dylib \
  ...
make
make install
```

doesn't work for me. And I found out they hard-code `openssl` for older Intel-based macOS builds!

So the ultimate solution is 

`brew edit sunshine-beta`

look for lines referencing `openssl` and **change every `openssl` into `openssl@3`**!!!

and add

```
    # this chunk of code might be optional
    if Hardware::CPU.arm?
      ENV.append "LDFLAGS", "-L#{Formula["openssl@3"].opt_lib}"
      ENV.append "CPPFLAGS", "-I#{Formula["openssl@3"].opt_include}"
    end
```

before

`    args << "-DCUDA_FAIL_ON_MISSING=OFF" if OS.linux?`

Last, `brew reinstall --build-from-source sunshine-beta`

**Comment by XiongjieDai** [comment]
If the above step didn't work, maybe this step works.

Step 2: Force Sunshine’s Build to Use the Correct Libraries
You want to ensure all references to OpenSSL point to /opt/homebrew/opt/openssl@3 instead of /usr/local/opt/openssl. There are two common approaches: (A) building manually from source, or (B) passing extra arguments via Homebrew.

(A) Building Manually from Source
Clone the Sunshine repo (or your fork) and enter it:

```
git clone https://github.com/LizardByte/Sunshine.git
cd Sunshine
# If you need a specific tag or branch, checkout it out here, e.g.:
# git checkout v2025.312.131644
```

Run CMake with explicit OpenSSL paths:

```
cmake -S . -B build \
  -DCMAKE_BUILD_TYPE=Release \
  -DOPENSSL_ROOT_DIR="/opt/homebrew/opt/openssl@3" \
  -DOPENSSL_SSL_LIBRARY="/opt/homebrew/opt/openssl@3/lib/libssl.dylib" \
  -DOPENSSL_CRYPTO_LIBRARY="/opt/homebrew/opt/openssl@3/lib/libcrypto.dylib" \
  -DCMAKE_INSTALL_PREFIX="/opt/homebrew" \
  -DBUILD_TESTING=ON   # or OFF if you want to skip tests
```

Compile and install:

```
cmake --build build
cmake --install build
```

(B) Forcing Correct Libraries via Homebrew
When installing from a Homebrew formula (e.g., sunshine-beta), you can pass additional CMake options after --. For example:

```
export OPENSSL_ROOT_DIR="/opt/homebrew/opt/openssl@3"
export LDFLAGS="-L/opt/homebrew/opt/openssl@3/lib"
export CPPFLAGS="-I/opt/homebrew/opt/openssl@3/include"

brew reinstall --build-from-source sunshine-beta \
  -- \
  -DOPENSSL_ROOT_DIR=/opt/homebrew/opt/openssl@3 \
  -DOPENSSL_SSL_LIBRARY=/opt/homebrew/opt/openssl@3/lib/libssl.dylib \
  -DOPENSSL_CRYPTO_LIBRARY=/opt/homebrew/opt/openssl@3/lib/libcrypto.dylib
```
Note: If the formula itself forces a /usr/local/opt/openssl path internally, these flags may be overridden. In that case, see Last Step (patch the formula).

**Comment by kayakyakr** [comment]
Unfortunately, none of these fixes worked for me so far. But seems like the right direction.

**Comment by ReenigneArcher** [comment]
That's the pre release

**Comment by alotofentropy** [comment]
I have attempted to do the build on a hackintosh (with an i7700 and a 6600) VM in Sequoia withe the attempted solutions with brew as above, but I still get similar errors. Kind of looks like we are on track with something, but I still cant solve it.  

[00.options.out.txt](https://github.com/user-attachments/files/19678857/00.options.out.txt)
[01.cmake.cc.txt](https://github.com/user-attachments/files/19678858/01.cmake.cc.txt)
[01.cmake.txt](https://github.com/user-attachments/files/19678856/01.cmake.txt)
[02.make.cc.txt](https://github.com/user-attachments/files/19678855/02.make.cc.txt)
[02.make.txt](https://github.com/user-attachments/files/19678859/02.make.txt)

**Comment by alhuges** [comment]
Same, None of these worked for me....

**Comment by ZSMX** [comment]
I faced the same problem on mac mini m4. make: *** [all] Error 2

**Comment by kairlec** [comment]
> I faced the same problem on mac mini m4. make: *** [all] Error 2

I'm using macOS 15.4 on an apple m4
The clang version from xcode 16.3 is 17.0.0 build 1700
I saw in my error log:
`/opt/homebrew/opt/icu4c@77/include/unicode/localpointer.h:561:26: error: 'auto' not allowed in template parameter until C++17`
So I used `brew edit sunshine-beta` and added `args << -DCMAKE_CXX_STANDARD=17`
Then run `brew install sunshine-beta` and it worked

**Comment by alhuges** [comment]
> > I faced the same problem on mac mini m4. make: *** [all] Error 2
> 
> I'm using macOS 15.4 on an apple m4 The clang version from xcode 16.3 is 17.0.0 build 1700 I saw in my error log: `/opt/homebrew/opt/icu4c@77/include/unicode/localpointer.h:561:26: error: 'auto' not allowed in template parameter until C++17` So I used `brew edit sunshine-beta` and added `args << "-DCMAKE_CXX_STANDARD=17"` Then run `brew install sunshine-beta` and it worked

It worked! Thanks

**Comment by ReenigneArcher** [comment]
Thank you! Homebrew must be messing with the value on their own. I have put up a PR https://github.com/LizardByte/Sunshine/pull/3797, but I don't know if it will fix the original issue reported here.

**Comment by nekitk** [comment]
Tried both 20 and 17, no change for me, still `'filesystem'/'cstddef' file not found`

**Comment by melgu** [comment]
Installing the sunshine-beta on an M1 with macOS 15.5 worked without requiring any changes 👍

**Comment by 74k1** [comment]
Can confirm. Worked on an M3 Max with macOS 15.4.2 as well. 👍

**Comment by TylerStegall** [comment]
I'm not able to install on MacOS 15.5. I get the same error 1 and error 2 messages...

**Comment by ReenigneArcher** [comment]
New errors are probably this: https://github.com/LizardByte/Sunshine/issues/3180#issuecomment-2924016998

**Comment by ReenigneArcher** [comment]
@bohemian-lh see https://github.com/LizardByte/Sunshine/blob/a857c8b7154491c0770b4c38c96463d4ce95419e/packaging/sunshine.rb#L237-L238

**Comment by Xryphon** [comment]
> New errors are probably this: [#3180 (comment)](https://github.com/LizardByte/Sunshine/issues/3180#issuecomment-2924016998)

Just wanted to say that the fix provided in this thread fixed the install issue (error code 2). Thanks!

**Comment by bohemian-lh** [comment]
> [@bohemian-lh](https://github.com/bohemian-lh) see
> 
> [Sunshine/packaging/sunshine.rb](https://github.com/LizardByte/Sunshine/blob/a857c8b7154491c0770b4c38c96463d4ce95419e/packaging/sunshine.rb#L237-L238)
> 
> Lines 237 to 238 in [a857c8b](/LizardByte/Sunshine/commit/a857c8b7154491c0770b4c38c96463d4ce95419e)
> 
>            icu4c must be installed to link against static Boost libraries, 
>            either install icu4c or use brew install sunshine --with-static-boost instead

I had install iuc4c@77 correctly. And I spent some time reviewing the complete logs. The issues likely stem from MiniUPnPC header file errors and Boost::Process namespace errors. Perhaps I need to try creating a temporary patch and installing an older version of Boost.

**Comment by jiangqing03** [comment]
the same problem on macmini m4: grep -B 30 -A 10 "error:" /Users/jiang-m4/Library/Logs/Homebrew/sunshine/02.make
gemini:好的，非常感谢你提供了这么详细的日志！这下问题就很清楚了。
你运行的 grep 命令找到了真正的错误，这比之前的 "make Error 2" 有用得多。
问题根源分析
从日志来看，你的编译失败是由两个不同的、核心的兼容性问题导致的，这与你正在使用的非常新的 macOS 15 (Sequoia) 和 Xcode 16 环境有直接关系。新系统带来了新版本的底层开发库（比如 Boost 和 miniupnpc），而 Sunshine 的代码暂时还没有跟上这些库的更新。
我们来分解一下这两个问题：

问题一：miniupnpc 库的头文件错误
/opt/homebrew/Cellar/miniupnpc/2.3.3/include/miniupnpc/upnpcommands.h:397:37: error: unknown type name 'size_t'
	•	错误原因：编译器在处理 upnpcommands.h 这个文件时，不认识 size_t 这个基本类型。size_t 通常在 C/C++ 的标准头文件（如 <cstddef> 或 <stddef.h>）中定义。
	•	为什么会发生：这通常意味着 upnpcommands.h 文件本身缺少了对必要标准库头文件的引用。在你的新版 macOS + Xcode 环境下，编译器对代码规范的要求可能更严格了，导致这个问题暴露出来。这其实是 miniupnpc 这个库本身的一个小缺陷，在最新环境下被触发了。

问题二：Boost.Process 库的版本不兼容
这是更严重的问题，出现了两种形式的错误：
	1	找不到头文件： fatal error: 'boost/process/v1.hpp' file not found
	2	    Sunshine 的代码尝试引用一个名为 boost/process/v1.hpp 的文件，但在你系统上由 Homebrew 安装的新版 Boost 库中，这个文件已经不存在了。它可能被重命名为 boost/process.hpp。
	3	找不到命名空间： error no member named 'v1' in namespace 'boost::process'
	4	    代码中使用了 boost::process::v1::... 这样的写法，期望访问 v1 这个版本号命名空间。然而，新版的 Boost 库已经移除了这个 v1 命名空间。
	•	错误原因：Sunshine 的源代码是为一个旧版本的 Boost.Process 库编写的。而 Homebrew 为你的新 macOS 系统安装了最新版本的 Boost 库。新旧版本之间 API（应用程序编程接口）发生了变化，导致代码无法通过编译。
总结与解决方案
你遇到的已经不是最初那个简单的 C++17 标准问题了，而是 Sunshine 源代码与核心依赖库（Boost, miniupnpc）之间的深度不兼容。
这种级别的问题无法通过修改 Homebrew 安装脚本来解决，因为它需要直接修改 Sunshine 的 C++ 源代码。

**Comment by ReenigneArcher** [comment]
> /opt/homebrew/Cellar/miniupnpc/2.3.3/include/miniupnpc/upnpcommands.h:397:37: error: unknown type name 'size_t'

If you see this, use sunshine-beta, it's already been fixed.

**Comment by jiangqing03** [comment]
> > /opt/homebrew/Cellar/miniupnpc/2.3.3/include/miniupnpc/upnpcommands.h:397:37: error: unknown type name 'size_t'
> 
> If you see this, use sunshine-beta, it's already been fixed.

It's works! thanks
