### PR TITLE
fix(upnp): support newer miniupnpc library

### PR DESCRIPTION
**Pull request by tgurr**
## Description
Fixes incompatibilities with newer version of miniupnpc library.

Trying to build with miniupnpc 2.3.3 (GCC15) I run into the following build failure the patch is intended to address:

```
[...]
In file included from /var/tmp/paludis/build/net-remote-sunshine-2025.122.141614-r1/work/sunshine-2025.122.141614/src/upnp.cpp:7:
/usr/x86_64-pc-linux-gnu/include/miniupnpc/upnpcommands.h:397:37: error: 'size_t' has not been declared
  397 |                                     size_t desclen,
      |                                     ^~~~~~
/usr/x86_64-pc-linux-gnu/include/miniupnpc/upnpcommands.h:26:1: note: 'size_t' is defined in header '<cstddef>'; this is probably fixable by adding '#include <cstddef>'
   25 | #include "miniupnpctypes.h"
  +++ |+#include <cstddef>
   26 | 
/usr/x86_64-pc-linux-gnu/include/miniupnpc/upnpcommands.h:469:36: error: 'size_t' has not been declared
  469 |                                    size_t desclen,
      |                                    ^~~~~~
/usr/x86_64-pc-linux-gnu/include/miniupnpc/upnpcommands.h:469:36: note: 'size_t' is defined in header '<cstddef>'; this is probably fixable by adding '#include <cstddef>'
/usr/x86_64-pc-linux-gnu/include/miniupnpc/upnpcommands.h:472:36: error: 'size_t' has not been declared
  472 |                                    size_t rHostlen,
      |                                    ^~~~~~
/usr/x86_64-pc-linux-gnu/include/miniupnpc/upnpcommands.h:472:36: note: 'size_t' is defined in header '<cstddef>'; this is probably fixable by adding '#include <cstddef>'
[...]
```
Complete build log: [sunshine-2025.122.141614_build.log](https://github.com/user-attachments/files/20493955/sunshine-2025.122.141614_build.log)

Not really sure if that's something that should rather be addressed in miniupnpc itself instead (which itself builds fine). Commit introducing it appears to be https://github.com/miniupnp/miniupnp/commit/83ac78c55af6d27c6e19a6e0de46da2d525d1a2d

## Type of Change
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Dependency update (updates to dependencies)
- [ ] Documentation update (changes to documentation)
- [ ] Repository update (changes to repository files, e.g. `.github/...`)

## Checklist
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added or updated the in code docstring/documentation-blocks for new or existing methods/components

### CODE REVIEW

**Comment by tgurr** [comment]
Considering

> Not really sure if that's something that should rather be addressed in miniupnpc itself instead (which itself builds fine). Commit introducing it appears to be https://github.com/miniupnp/miniupnp/commit/83ac78c55af6d27c6e19a6e0de46da2d525d1a2d

I've submitted a PR accordingly https://github.com/miniupnp/miniupnp/pull/838

**Comment by tgurr** [comment]
Closing in favor of ‎miniupnpc upstream commit https://github.com/miniupnp/miniupnp/commit/e263ab6f56c382e10fed31347ec68095d691a0e8

**Comment by rubin55** [comment]
I saw this PR was closed in favor of miniupnpc itself including `stddef.h` in their `uicommands.h`, which merged to their master about 3 weeks ago. However, after upgrade of `miniupnpc` to v2.3.3 just now, I tried to rebuild latest sunshine master, but this now fails with the following message:

```
/makepkg.builddir/sunshine-git/src/Sunshine/src/upnp.cpp
In file included from /tmp/makepkg.builddir/sunshine-git/src/Sunshine/src/upnp.cpp:7:
/usr/include/miniupnpc/upnpcommands.h:397:37: error: ‘size_t’ has not been declared
  397 |                                     size_t desclen,
      |                                     ^~~~~~
/usr/include/miniupnpc/upnpcommands.h:469:36: error: ‘size_t’ has not been declared
  469 |                                    size_t desclen,
      |                                    ^~~~~~
/usr/include/miniupnpc/upnpcommands.h:472:36: error: ‘size_t’ has not been declared
  472 |                                    size_t rHostlen,
      |                                    ^~~~~~
[266/364] Building CUDA object CMakeFi...shine.dir/src/platform/linux/cuda.cu.o
nvcc warning : incompatible redefinition for option 'std', the last value of this option was used
nvcc warning : Support for offline compilation for architectures prior to '<compute/sm/lto>_75' will be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
[285/364] Building CXX object CMakeFiles/sunshine.dir/src/confighttp.cpp.o
ninja: build stopped: subcommand failed.
==> ERROR: A failure occurred in build().
```

If I look at `/usr/include/miniupnpc/uicommands.h` which is part of the `miniupnpc` v2.3.3-1 package, I don't see that added `stddef.h` include there (I couldn't quickly determine if it should have been).

**Comment by ReenigneArcher** [comment]
@tgurr

Could you re-open this? It seems to be taking miniupnp forever to create a patch release with the fix, and this is now affecting Arch Linux and Windows builds.

**Comment by tgurr** [comment]
> @tgurr
> 
> Could you re-open this? It seems to be taking miniupnp forever to create a patch release with the fix, and this is now affecting Arch Linux and Windows builds.

I'm sorry I've already deleted the clone/repo as I thought it's not the correct place to fix/workaround the issue so I can't easily reopen the issue. Feel free to just take the patch and apply it if wanted. But wouldn't it rather make sense to open an issue at arch to include the patch to their miniupnpc package, that should be quite common practice on distros (and it's what we did on Exherbo) as upstreams are often slacking with their (bugfix) releases and/or have hardcoded schedules.
